config/routes.rb
Rails.application.routes.draw do
  root 'programmers#index'
  resources :programmers

end

app/models/programmer.rb
class Programmer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/programmers_controller.rb
class ProgrammersController < ApplicationController
  def index
    @programmers = Programmer.all
  end

  def show
    @programmer = Programmer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_date(date)
    if date
      date.strftime("%B %d, %Y")
    end
  end
end

app/helpers/programmers_helper.rb
module ProgrammersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProgrammerProfilePartials</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>


<div class="container">

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-brand">
      Programmers We L<span class="glyphicon glyphicon-heart"></span>ve
    </div>
  </nav>

  <%= yield %>

</div>

</body>
</html>

app/views/programmers/index.html.erb
<h1>Our Favorite Programmers</h1>

<ul class="list-group">
<% @programmers.each do |programmer| %>
  <%= link_to programmer_path(programmer) do %>
  <p class="list-group-item programmer-item">
    <%= image_tag programmer.image, width: '70px' %>
    <%= programmer.name %>
  </p>
  <% end %>
<% end %>
</ul>

app/views/programmers/show.html.erb
<%= link_to '<span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>'.html_safe, root_path %>

<h3>
  <%= @programmer.name %> | <%= formatted_date(@programmer.birth_date) %> - <%= formatted_date(@programmer.death_date) %>
</h3>

<div class="row jumbotron">

  <div class="col-md-3">
    <%= image_tag @programmer.image, height: '250px', class:"profile-image" %>
  </div>

  <div class="col-md-9 programmer-info">

    <p>
    <strong>Home Country:</strong> <%= @programmer.home_country %><br>
    </p>

    <p>
    <strong>Quote:</strong> <%= @programmer.quote %><br>
    </p>

    <p>
    <strong>Claim To Fame:</strong> <%= @programmer.claim_to_fame %>
    </p>

    <p>
    <%= link_to "Learn more about #{@programmer.name}", @programmer.wikipedia_page, target: '_blank' %>
    </p>

  </div>
</div>